### ISSUE TITLE
Implement convenience upsert

### ISSUE THREAD

**Issue by EthanLozano** [SwifQL/Bridges#12]
It would be nice if Bridges natively implemented a convenience method for `upsert`, since this is a pretty common command.

I'm not sure if this is the correct repo/layer, but it seems like the implementation would go in Bridges/Helpers/TableUpsert.swift

The desired API would be similar to `TableInsert.swift` and `TableUpdate.swift` except you would also specify the conflict column(s).

I got the gnarly upsert query below to work for postgres. I gradually built this command from SwifQL example test code, although TableInsert/TableUpdate seem to suggest that this command can be simplified.

```
        SwifQL
            .insertInto(MyTable.table, fields: \MyTable.$id,
                        \MyTable.$myNormalField,
                        \MyTable.$myNullableField,
                        \MyTable.$myBoolField)
            .values
            .values(obj.id,
                    obj.myNormalField,
                    obj.myNullableField,
                    SwifQLBool(obj.myBoolField))
            .on.conflict(MyTable.column(MyTable.Columns.id.rawValue)).do
            .update
            .set[items: MyTable.$myNormalField == obj.myNormalField,
                 MyTable.$myNullableField == obj.myNullableField ?? SwifQLNull,
                 MyTable.$myBoolField == obj.myBoolField]
```

**Comment by MihaelIsaev** [comment]
@EthanLozano thank you for the inspiration, it is now available since [1.0.0-rc.4.11.0](https://github.com/SwifQL/Bridges/releases/tag/1.0.0-rc.4.11.0)

**Comment by EthanLozano** [comment]
That was quick. Thanks!

**Comment by EthanLozano** [comment]
After some trial and error, I got this implementation to work. I figured I would post some documentation here for posterity. Let me know if there is a way to perform an upsert on multiple columns by specifying the column names rather than a table constraint.

### When there conflict is only on a single column
```
myTable.upsert(conflictColumn: \MyTable.$id,
               excluding: \MyTable.$id,
               on: .psqlEnvironment, on: req)
```

### When the conflict happens across multiple columns
```
myTupleTable.upsert(conflictConstraint: "my_tuple_table_pkey",
                    excluding: \MyTupleTable.$id1, \MyTupleTable.$id2,
                    on: .psqlEnvironment, on: req)
```

The conflict constraint needs to exist on the table. For instance:
```
updateBuilder
    .addPrimaryKey(to: "id1", "id2")
    .execute(on: conn)
```

Running `\d my_tuple_table` in psql should yield the name of the index constraint:
```
Indexes:
    "my_tuple_table_pkey" PRIMARY KEY, btree (id1, id2)
```

**Comment by MihaelIsaev** [comment]
First of all if you choose `conflictColumn: \MyTable.$id` there is no need to write `excluding: \MyTable.$id`

so this code 
```swift
myTable.upsert(conflictColumn: \MyTable.$id,
               excluding: \MyTable.$id,
               on: .psqlEnvironment, on: req)
```
could be a little bit shorter
```swift
myTable.upsert(conflictColumn: \MyTable.$id, on: .psqlEnvironment, on: req)
```

If to speak about `ON CONFLICT` for multiple columns, it looks like it doesn't work out of the box

so as far as I googled it this construction will not work unfortunately

```sql
ON CONFLICT (id1, id2)
```

So yeah it looks like the only way is to check constraint. Please correct me if I'm wrong.

At this point we have an ability to write constraint name only manually as a string. I think we could implement some convenience record like

```swift
@Constraint("my_tuple_table_pkey")
var tupleTablePKey: String
/// it will be pseudo variable, idk which type to use here,
/// String is just for example, maybe we could store here something and use Constraint type for it
```

to use it kinda like this

```swift
newUser.upsert(conflictConstraint: \User.$tupleTablePKey, on: conn)
```

If to speak about constraint name, we could set it in advance during migration. examples:
```swift
updateBuilder.addCheck(constraintName: String?, expression: SwifQLable)
updateBuilder.createIndex(unique: Bool, name: String?, items: IndexItem, type: IndexType?, where: SwifQLable?)
```

it seems that for `ADD PRIMARY KEY` command there are no way to set constraint name in advance, or if you know how I could add it. Maybe custom name not needed here cause postgres always use just `table_name_pkey` by default and we could just be sure that this default name will be used in advance.

I also just tested in Postico, it seems that `PRIMARY KEY` can't be added to two columns. If we add constraint to two columns it seems that it is just `INDEX`, not `PRIMARY KEY`.

@EthanLozano what do you think?

**Comment by EthanLozano** [comment]
@MihaelIsaev I think it would be nice if users could specify the primary key of a table within their table's declaration. Then, I think it would be nice if Bridges could process that information automatically (without the user having to manually feed the information back to Bridges).

I don't have a strong opinion on how the Bridges API collects table information from the user, whether it be through an attribute, variable, or method.

Below is one possible solution. This code does not compile since I didn't have the patience to figure types for columns, but hopefully you get the idea:

```
struct MultipleColumnConstraint {
    let columns: [Column]
    let name: String
}

enum PrimaryKey {
    case single(Column)
    case multiple(MultipleColumnConstraint)
}

protocol PrimaryKeyTable: Table {
    static var primaryKey: PrimaryKey { get }
}

extension PrimaryKeyTable {
    public func upsert(on conn: BridgeConnection) -> EventLoopFuture<Self> {
        switch Self.primaryKey {
        case .single(let column):
            return upsert(
                conflictColumn: column,
                on: conn)
        case .multiple(let constraint):
            return upsert(
                conflictConstraint: constraint.name,
                excluding: constraint.columns,
                on: conn)
        }
    }

    // other upsert methods
}

final class MyTupleTable: PrimaryKeyTable {
    static let primaryKey = PrimaryKey.multiple(MultipleColumnConstraint(
                                                    columns: [\MyTupleTable.$id1, \MyTupleTable.$id2],
                                                    name: "my_tuple_table_pkey"))

    @Column("id1")
    var id1: UUID

    @Column("id2")
    var id2: UUID

    // ...
}

myTupleTable.upsert(on: conn)
```

Alternatively, maybe you have a separate protocol for each type of primary key?
```
protocol SingleColumnPrimaryKeyTable: Table {
    static var primaryKey: Column { get }
}

protocol MultipleColumnPrimaryKeyTable: Table {
    static var primaryKey: MultipleColumnConstraint { get }
}
```
